(function(){
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const localAccount=()=>JSON.parse(localStorage.getItem('nexoraAccount')||'{}');
  const localProfile=()=>JSON.parse(localStorage.getItem('nexoraProfile')||'{}');
  const fullName=a=>[a.first_name,a.last_name].filter(Boolean).join(' ')||a.name||'Votre compte';
  function inject(){
    if(document.getElementById('nxAccountModal'))return;
    const style=document.createElement('style');style.textContent=`#nxAccountModal{position:fixed;inset:0;background:rgba(10,15,25,.48);backdrop-filter:blur(5px);z-index:9999;display:none;align-items:center;justify-content:center;padding:20px}#nxAccountModal.open{display:flex}.nx-account-box{width:min(620px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;box-shadow:0 30px 90px rgba(0,0,0,.25);padding:26px;font-family:DM Sans,Arial}.nx-account-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px}.nx-account-head h2{margin:3px 0 5px;font:800 26px Manrope,Arial;color:#151a27}.nx-account-close{border:0;background:#f1f3f6;border-radius:10px;width:38px;height:38px;font-size:22px;cursor:pointer}.nx-account-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.nx-account-field{border:1px solid #e4e7ec;border-radius:13px;padding:13px}.nx-account-field small{display:block;color:#7a8290;font-size:11px;font-weight:800;text-transform:uppercase;margin-bottom:5px}.nx-account-field strong{font-size:14px;color:#202633;word-break:break-word}.nx-account-section{margin-top:22px}.nx-account-section h3{font-size:14px;margin:0 0 10px;color:#202633}.nx-quiz-list{display:flex;flex-wrap:wrap;gap:8px}.nx-quiz-pill{background:#f4f6f8;border-radius:999px;padding:8px 11px;font-size:12px;color:#333b49}.nx-account-note{margin-top:18px;color:#737b89;font-size:12px;line-height:1.5}@media(max-width:560px){.nx-account-grid{grid-template-columns:1fr}}`;
    document.head.appendChild(style);
    const modal=document.createElement('div');modal.id='nxAccountModal';modal.innerHTML=`<div class="nx-account-box" role="dialog" aria-modal="true" aria-labelledby="nxAccountTitle"><div class="nx-account-head"><div><span style="font-size:10px;font-weight:900;color:#7b8492;letter-spacing:.12em">MON COMPTE NEXORA</span><h2 id="nxAccountTitle">Votre profil</h2><p id="nxAccountStatus" style="margin:0;color:#697282;font-size:13px">Chargement…</p></div><button class="nx-account-close" id="nxAccountClose" aria-label="Fermer">×</button></div><div class="nx-account-grid" id="nxAccountGrid"></div><div class="nx-account-section"><h3>Profil de matching</h3><div class="nx-quiz-list" id="nxQuizList"></div></div><p class="nx-account-note">Le mot de passe n'est jamais affiché ici. Il doit rester géré par le système d'authentification, pas stocké dans le profil public.</p></div>`;document.body.appendChild(modal);
    modal.addEventListener('click',e=>{if(e.target===modal)close()});document.getElementById('nxAccountClose').onclick=close;
  }
  function close(){document.getElementById('nxAccountModal')?.classList.remove('open')}
  async function load(){
    const a=localAccount(),p=localProfile();let row=null,quiz=null;
    try{if(window.NexoraSupabase){const c=await window.NexoraSupabase.getClient();const s=await c.auth.getSession();const uid=s.data?.session?.user?.id||localStorage.getItem('nexoraSupabaseUserId');if(uid){const r=await c.from('profiles').select('*').eq('id',uid).maybeSingle();if(!r.error)row=r.data;const q=await c.from('quiz_profiles').select('answers').eq('profile_id',uid).maybeSingle();if(!q.error)quiz=q.data?.answers||null;}}}catch(e){console.warn('[Nexora] account profile load failed',e)}
    row=row||{first_name:a.first_name,last_name:a.last_name,username:a.username,phone:a.phone,email:a.email,role:a.role,company:a.company,birth_date:a.birth_date,otp_channel:a.otp_channel,profile_complete:a.profileComplete};quiz=quiz||p;
    const name=fullName(row);document.getElementById('nxAccountTitle').textContent=name;document.getElementById('nxAccountStatus').textContent=row.profile_complete?'Profil complet':'Profil en cours';
    const fields=[['Prénom',row.first_name],['Nom',row.last_name],['Pseudo',row.username],['Poste / activité',row.role],['Entreprise',row.company||'Non renseignée'],['Téléphone',row.phone],['Adresse e-mail',row.email||'Non renseignée'],['Date de naissance',row.birth_date||'Non renseignée'],['Code reçu par',row.otp_channel==='whatsapp'?'WhatsApp':'SMS']];
    document.getElementById('nxAccountGrid').innerHTML=fields.map(([k,v])=>`<div class="nx-account-field"><small>${esc(k)}</small><strong>${esc(v||'—')}</strong></div>`).join('');
    const entries=Object.entries(quiz||{}).filter(([k])=>k!=='role');document.getElementById('nxQuizList').innerHTML=entries.length?entries.map(([k,v])=>`<span class="nx-quiz-pill"><b>${esc(k)}:</b> ${esc(v)}</span>`).join(''):'<span class="nx-quiz-pill">Aucune réponse enregistrée</span>';
  }
  function open(){inject();document.getElementById('nxAccountModal').classList.add('open');load()}
  function init(){inject();const targets=['.top-user','.side-user'];targets.forEach(sel=>document.querySelectorAll(sel).forEach(el=>{el.style.cursor='pointer';el.setAttribute('role','button');el.setAttribute('tabindex','0');el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')open()})}));}
  window.NexoraOpenAccount=open;window.NexoraAccountProfile={load};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
