(function(){
const found=[];let timer=null,active=true;const root=()=>document.querySelector('.prospect-table');const alerts=()=>document.querySelector('.alerts');
const parseScore=v=>{const n=parseFloat(String(v??'').replace('%',''));return Number.isFinite(n)&&n>=0&&n<=100?Math.round(n):null};
const demoScore=p=>{const raw=String(p?.id||p?.handle||p?.name||'prospect');let h=0;for(let i=0;i<raw.length;i++)h=(h*31+raw.charCodeAt(i))>>>0;return 55+(h%41)};
const normalize=p=>{const s=parseScore(p?.matchScore??p?.score??p?.match) ?? demoScore(p);return {...p,matchScore:s,score:s,match:`${s}%`};};
function list(){const prepared=(()=>{try{return JSON.parse(localStorage.getItem('nexoraPreparedMatches')||'[]')}catch{return []}})();return (prepared.length?prepared:(window.NexoraMatching?.matches('')||[])).map(normalize)}
function detail(p){const idx=window.NexoraProspectData?.findIndex(x=>x.id===p.id);if(window.NexoraOpenProspect)window.NexoraOpenProspect(idx>=0?idx:0,normalize(p))}
function render(){const r=root();if(!r)return;r.querySelectorAll('.prospect.nexora-auto-prospect').forEach(x=>x.remove());found.slice().reverse().forEach(p=>{p=normalize(p);const row=document.createElement('div');row.className='prospect nexora-auto-prospect';row._nexoraProspect=p;row.dataset.matchScore=String(p.matchScore);row.style.cssText='cursor:pointer;transition:transform .2s ease,box-shadow .2s ease,background .2s ease';row.innerHTML='<div class="person"><div class="person-avatar a1">'+(p.initial||p.name?.[0]||'N')+'</div><div><strong>'+p.handle+'</strong><small>'+p.name+'</small></div></div><span class="source">'+p.source+'</span><p>'+p.need+'</p><b class="match high">'+p.match+'</b><button type="button" class="auto-detail">Voir les détails →</button>';row.onclick=e=>{if(!e.target.closest('button'))detail(p)};row.querySelector('.auto-detail').onclick=e=>{e.stopPropagation();detail(p)};row.onmouseenter=()=>{row.style.transform='translateY(-2px)';row.style.boxShadow='0 8px 24px rgba(17,24,39,.10)';row.style.background='#fafbfc'};row.onmouseleave=()=>{row.style.transform='';row.style.boxShadow='';row.style.background=''};r.appendChild(row)});const c=document.getElementById('prospectsCount');if(c)c.textContent=String(found.length)}
function notify(p){p=normalize(p);const a=alerts();if(!a)return;const n=document.createElement('div');n.className='alert nexora-auto-alert';n.innerHTML='<div><strong>'+p.match+' match · '+p.name+'</strong><p>Nouveau besoin détecté : '+p.need+'</p><small>Détecté à l’instant · <button type="button" class="alert-detail">Voir le prospect →</button></small></div><span class="nav-badge">NEW</span>';n.querySelector('.alert-detail').onclick=e=>{e.stopPropagation();detail(p)};n.onclick=()=>detail(p);a.prepend(n);while(a.children.length>10)a.lastElementChild.remove()}
function shuffle(items){return items.slice().sort(()=>Math.random()-.5)}
async function add(){if(!active)return;const matches=list();if(!matches.length)return;const recent=new Set(found.slice(-10).map(p=>p.baseId||p.id));let pool=shuffle(matches.filter(p=>!recent.has(p.id)));if(!pool.length)pool=shuffle(matches);const profile=JSON.parse(localStorage.getItem('nexoraProfile')||'{}');let chosen=pool[0];try{if(window.NexoraAI?.rank){const ai=await window.NexoraAI.rank(profile,'',pool);const byId=new Map(pool.map(x=>[String(x.id||x.handle||x.name),x]));const ranked=ai.map(m=>{const base=byId.get(String(m.id));return base?normalize({...base,aiReason:m.reason||'' ,matchScore:m.score}):null}).filter(Boolean);if(ranked.length){const nonRecent=ranked.find(x=>!recent.has(x.id));chosen=nonRecent||ranked[0]}}}catch(e){console.warn('Auto-Match AI unavailable; using profile-filtered demo rotation',e)}
const p=normalize({...chosen,baseId:chosen.id,id:'auto-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)});found.push(p);while(found.length>10)found.shift();window.NexoraProspectData=found.slice();render();notify(p)}
function start(){if(timer)clearInterval(timer);active=true;setTimeout(()=>{if(!window.NexoraMatching){start();return}add();timer=setInterval(add,18000)},1000)}
window.NexoraAutoMatch={start,stop:()=>{active=false;if(timer)clearInterval(timer)},add,found};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
