(function(){
  function openContact(name,need){
    let m=document.getElementById('contactWorkspace');
    if(!m){m=document.createElement('div');m.id='contactWorkspace';m.style.cssText='position:fixed;inset:0;background:rgba(15,23,42,.48);backdrop-filter:blur(6px);z-index:500;display:flex;align-items:center;justify-content:center;padding:20px';document.body.appendChild(m)}
    const safeName=name||'Prospect'; const safeNeed=need||'votre besoin';
    m.innerHTML='<div style="width:min(720px,96vw);background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 30px 90px rgba(0,0,0,.2);font-family:DM Sans,Arial;color:#182033"><div style="padding:22px 26px;border-bottom:1px solid #e9ecf2;display:flex;align-items:center"><div><span style="font-size:11px;font-weight:800;letter-spacing:.12em;color:#737c8d">NEXORA AI · CONTACT</span><h2 style="margin:5px 0 0;font:800 24px Manrope,Arial">'+safeName+'</h2></div><button id="closeContact" style="margin-left:auto;border:0;background:#f1f3f7;border-radius:10px;width:38px;height:38px;font-size:20px;cursor:pointer">×</button></div><div style="padding:26px"><div style="background:#f7f8fa;border-radius:16px;padding:16px;margin-bottom:18px"><small style="color:#737c8d;font-weight:700">NEED DETECTED</small><div style="font-weight:700;margin-top:5px">'+safeNeed+'</div></div><div id="contactMessages" style="display:grid;gap:12px;min-height:120px"><div style="justify-self:start;background:#f1f3f7;border-radius:16px 16px 16px 4px;padding:13px 16px;max-width:80%"><strong style="font-size:12px">Nexora AI</strong><p style="margin:5px 0 0;line-height:1.5">J’ai préparé un premier message adapté à ce prospect.</p></div></div><div style="margin-top:18px"><textarea id="contactText" rows="4" style="width:100%;box-sizing:border-box;border:1px solid #d9deea;border-radius:14px;padding:14px;font:500 14px DM Sans;resize:vertical" placeholder="Écrivez votre message…">Bonjour '+safeName+', j’ai vu que vous recherchez '+safeNeed.toLowerCase()+'. Je peux vous aider sur ce projet. Seriez-vous disponible pour en discuter ?</textarea><div style="display:flex;gap:10px;margin-top:10px"><button id="copyContact" style="border:1px solid #d9deea;background:#fff;border-radius:11px;padding:12px 15px;font-weight:800;cursor:pointer">Copier</button><button id="sendContact" style="flex:1;border:0;background:#111827;color:#fff;border-radius:11px;padding:12px 15px;font-weight:800;cursor:pointer">Envoyer · Démo</button></div></div><p style="font-size:11px;color:#7b8494;margin:14px 0 0">Mode démo : aucun message réel n’est envoyé.</p></div></div>';
    m.style.display='flex';
    m.querySelector('#closeContact').onclick=()=>m.style.display='none';
    m.querySelector('#copyContact').onclick=()=>navigator.clipboard?.writeText(m.querySelector('#contactText').value);
    m.querySelector('#sendContact').onclick=()=>{const b=m.querySelector('#sendContact');b.textContent='✓ Message envoyé · Démo';b.disabled=true;const box=m.querySelector('#contactMessages');const p=document.createElement('div');p.style.cssText='justify-self:end;background:#111827;color:#fff;border-radius:16px 16px 4px 16px;padding:13px 16px;max-width:80%;line-height:1.5';p.textContent=m.querySelector('#contactText').value;box.appendChild(p)};
  }
  window.NexoraContact=openContact;
  document.addEventListener('click',e=>{const b=e.target.closest('#contactProspect');if(!b)return;const modal=document.getElementById('prospectModal');const title=modal?.querySelector('h2')?.textContent||'Prospect';const need=modal?.querySelector('h3')?.textContent||'votre besoin';openContact(title,need)});
})();