(function(){
const profile=()=>JSON.parse(localStorage.getItem('nexoraProfile')||'{}');
const n=s=>(s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const catalog=[
{id:'kivu-digital',category:'developer',keywords:['developpeur','developer','web','site','application','logiciel','frontend','backend'],role:'Développeur',skills:['Développement web'],sector:['Tech'],need:'Recherche un développeur web pour créer un site internet',name:'Kivu Digital',handle:'@kivu_digital',location:'Kinshasa, RDC',source:'LinkedIn'},
{id:'nova-events',category:'photographer',keywords:['photographe','photo','videaste','mariage','evenement'],role:'Photographe / Vidéaste',skills:['Vidéo & Photo'],sector:['Médias & Création'],need:'Recherche un photographe professionnel pour un événement',name:'Nova Events',handle:'@nova_events',location:'Kinshasa, RDC',source:'Instagram'},
{id:'studio-lemba',category:'designer',keywords:['designer','design','ui','ux','branding','graphiste'],role:'Designer / Créatif',skills:['UI/UX & Design','Branding & Création'],sector:['Médias & Création'],need:'Recherche un designer pour une identité visuelle',name:'Studio Lemba',handle:'@studio_lemba',location:'Kinshasa, RDC',source:'Instagram'},
{id:'maison-m',category:'marketing',keywords:['marketing','communication','reseaux','social','community'],role:'Marketing / Communication',skills:['Marketing & Réseaux sociaux'],sector:['Commerce'],need:'Recherche un spécialiste pour gérer les réseaux sociaux',name:'Maison M',handle:'@maison_m',location:'Kinshasa, RDC',source:'Facebook'},
{id:'afrimarket',category:'commercial',keywords:['commercial','vente','sales','prospection','business'],role:'Commercial',skills:['Vente & Business'],sector:['Commerce'],need:'Recherche un commercial pour développer les ventes',name:'AfriMarket',handle:'@afr_imarket',location:'Kinshasa, RDC',source:'Facebook'},
{id:'business-ctg',category:'consultant',keywords:['consultant','conseil','strategie','expert'],role:'Consultant / Expert',skills:['Conseil & Stratégie'],sector:['Finance','Immobilier'],need:'Recherche un consultant pour accompagner son entreprise',name:'Business CTG',handle:'@business_ctg',location:'Kinshasa, RDC',source:'LinkedIn'}];
function cat(){const p=profile(),r=n(p.role),s=n(p.skills);if(r.includes('developpeur')||s.includes('developpement web'))return'developer';if(r.includes('photographe')||s.includes('video')||s.includes('photo'))return'photographer';if(r.includes('designer')||s.includes('ui/ux')||s.includes('branding'))return'designer';if(r.includes('marketing')||s.includes('reseaux sociaux'))return'marketing';if(r.includes('commercial')||s.includes('vente'))return'commercial';if(r.includes('consultant')||s.includes('conseil'))return'consultant';return''}
function text(p){return n([p.need,p.name,p.role,p.skills,p.sector,p.keywords].flat().join(' '))}
function terms(q){return n(q).split(/[^a-z0-9]+/).filter(x=>x.length>2)}
function matches(query=''){const c=cat(),qt=terms(query);let list=c?catalog.filter(p=>p.category===c):catalog.slice();if(qt.length)list=list.filter(p=>qt.some(t=>text(p).includes(t)));return list.map(p=>{let score=45;if(c)score+=30;if(qt.length)score+=qt.filter(t=>text(p).includes(t)).length*10;return {...p,match:Math.min(99,score)+'%',initial:p.name[0]}}).sort((a,b)=>parseInt(b.match)-parseInt(a.match))}
window.NexoraMatching={matches,profile,catalog,categoryForProfile:cat};
})();
