const profile=JSON.parse(localStorage.getItem('nexoraProfile')||'{}');const account=JSON.parse(localStorage.getItem('nexoraAccount')||'{}');const name=account.name||'Votre compte';const role=profile.role||'Professionnel';const zone=profile.zone||'International';const clients=profile.clients||'PME';const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};
set('sideName',name);set('topName',name);set('sideAvatar',name[0]?.toUpperCase()||'N');set('topAvatar',name[0]?.toUpperCase()||'N');set('welcomeTitle',`Good evening, ${name}.`);set('welcomeSub',`${role} · ${zone}. Nexora continue de surveiller les opportunités qui correspondent à votre profil.`);set('profileRole',role);set('profileMeta',`${zone} · ${clients}`);set('profileAvatar',role[0]?.toUpperCase()||'P');
function toast(msg){let t=$('#workspaceToast');if(!t){t=document.createElement('div');t.id='workspaceToast';t.style.cssText='position:fixed;right:24px;bottom:24px;z-index:200;padding:13px 16px;background:#151a27;color:#fff;border-radius:12px;font:600 14px DM Sans,Arial;box-shadow:0 15px 40px #0003';document.body.appendChild(t)}t.textContent=msg;t.style.opacity=1;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.opacity=0,2800)}
/* Sidebar = separate workspace views while staying in one app. */
const groups={dashboard:['.heading-row','.stats','.search-card','.automation','.lower-grid','.notifications-panel'],find:['.heading-row','.search-card'],auto:['.heading-row','.automation','.notifications-panel'],prospects:['.heading-row','.lower-grid'],messages:['.heading-row','.notifications-panel'],settings:['.heading-row','.settings']};
const titles={dashboard:['DASHBOARD',`Good evening, ${name}.`,'Nexora travaille en arrière-plan pour vous.'],find:['NEXORA AI · FIND','Find your next client.','Recherchez vous-même une opportunité. Nexora analyse votre demande avant de proposer des résultats.'],auto:['NEXORA AI · AUTOMATCH','Auto-Match','Nexora surveille continuellement les opportunités compatibles avec votre profil.'],prospects:['PROSPECTS','People who may need what you offer','Les prospects apparaissent ici uniquement après une recherche manuelle avec Find.'],messages:['NOTIFICATIONS','Latest matches','Les notifications apparaissent uniquement quand Auto-Match détecte un nouveau profil.'],settings:['SETTINGS','Preferences','Contrôlez votre espace Nexora et votre recherche automatique.']};
function view(v){const keep=groups[v]||groups.dashboard;const all=new Set(Object.values(groups).flat());all.forEach(sel=>{$$(sel).forEach(e=>e.style.display='none')});keep.forEach(sel=>{$$(sel).forEach(e=>e.style.display='')});const h=$('.heading-row');if(h&&titles[v]){const e=h.querySelector('.eyebrow'),t=h.querySelector('h1'),p=h.querySelector('p');if(e)e.textContent=titles[v][0];if(t)t.textContent=titles[v][1];if(p)p.textContent=titles[v][2]}$$('.nav-item').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+v));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();view(a.getAttribute('href').slice(1))}));
/* Dashboard prospect list starts empty. Find is the only way to populate it. */
const rows=$$('.prospect');rows.forEach(r=>r.style.display='none');const table=$('.prospect-table');if(table){let empty=document.createElement('div');empty.id='prospectEmpty';empty.className='empty-prospect-state';empty.style.cssText='padding:38px 20px;text-align:center;color:#687287;border:1px dashed #d8deea;border-radius:16px;margin-top:12px';empty.innerHTML='<strong style="display:block;font-size:18px;color:#182033;margin-bottom:8px">Aucun prospect trouvé</strong><span style="font-size:14px">Lancez une recherche manuelle dans Find pour afficher les prospects.</span>';table.appendChild(empty)}
/* Move the idea of Latest matches under Auto-Match: static notification cards are hidden until detection. */$$('.notifications-panel .alerts article').forEach(a=>a.style.display='none');
let auto=true,autoSec=0;function setAuto(v){auto=v;$$('.toggle').forEach(b=>b.classList.toggle('on',v));const mini=$('.ai-mini strong'),small=$('.ai-mini small'),live=$('.automation .live');if(mini)mini.textContent=v?'Auto-Match active':'Auto-Match paused';if(small)small.textContent=v?'Recherche continue':'Recherche annulée';if(live)live.textContent=v?'LIVE':'PAUSED';$$('#autoToggle,.toggle').forEach(b=>b.setAttribute('aria-pressed',String(v)));$$('.auto-cancel').forEach(b=>b.textContent=v?'Annuler la recherche':'Relancer la recherche');toast(v?'Auto-Match relancé.':'Recherche Auto-Match annulée.')}
let autoCancel=document.createElement('button');autoCancel.className='auto-cancel';autoCancel.textContent='Annuler la recherche';autoCancel.style.cssText='margin-left:auto;border:1px solid #d8deea;background:#fff;border-radius:10px;padding:10px 14px;font:700 13px DM Sans,Arial;cursor:pointer';const automation=$('.automation');if(automation&&!automation.querySelector('.auto-cancel'))automation.appendChild(autoCancel);autoCancel.addEventListener('click',()=>setAuto(!auto));$('#autoToggle')?.addEventListener('click',()=>setAuto(!auto));setAuto(true);
setInterval(()=>{if(!auto)return;autoSec++;const txt=autoSec<60?`scan il y a ${autoSec}s`:'scan continu';set('scanTimer',txt)},1000);
/* 15-second minimum manual Find analysis. */
const input=$('#findInput'),button=$('#findButton'),overlay=$('#searchLoading');let running=false,timer,interval;function progressUI(){if(!overlay)return null;let box=overlay.querySelector('.nx-progress');if(box)return box;box=document.createElement('div');box.className='nx-progress';box.style.cssText='width:min(520px,88vw);margin-top:20px';box.innerHTML='<div style="display:flex;justify-content:space-between;color:#111827;font:700 14px DM Sans"><span id="nxStage">Analyse de votre demande…</span><b id="nxPct">0%</b></div><div style="height:8px;background:#e7eaf0;border-radius:99px;margin:10px 0 18px;overflow:hidden"><i id="nxBar" style="display:block;width:0;height:100%;background:#111827;border-radius:99px"></i></div><div style="display:grid;gap:7px;text-align:left;font:600 13px DM Sans;color:#6d7482"><span id="nx1">○ Lecture de la demande</span><span id="nx2">○ Scan des opportunités</span><span id="nx3">○ Comparaison des profils</span><span id="nx4">○ Classement des meilleurs matchs</span></div><button id="nxCancel" style="margin-top:20px;border:1px solid #cfd5df;background:#fff;border-radius:10px;padding:11px 16px;font:700 13px DM Sans;cursor:pointer">Annuler la recherche</button>';overlay.appendChild(box);$('#nxCancel').onclick=cancel;return box}
function stage(n,title){set('nxStage',title);['Lecture de la demande','Scan des opportunités','Comparaison des profils','Classement des meilleurs matchs'].forEach((x,i)=>{const e=$('#nx'+(i+1));if(e){e.textContent=(i<n?'✓ ':i===n?'• ':'○ ')+x;e.style.color=i<=n?'#111827':'#70798a'}})}
function startSearch(){if(running||!overlay)return;running=true;view('find');overlay.classList.remove('hidden');progressUI();stage(0,'Analyse de votre demande…');const start=Date.now();interval=setInterval(()=>{const ms=Date.now()-start,p=Math.min(98,Math.floor(ms/15000*100));if($('#nxBar'))$('#nxBar').style.width=p+'%';set('nxPct',p+'%');if(ms<3500)stage(0,'Analyse de votre demande…');else if(ms<7000)stage(1,'Scan des opportunités…');else if(ms<10500)stage(2,'Comparaison des profils…');else stage(3,'Classement des meilleurs matchs…')},200);timer=setTimeout(()=>{clearInterval(interval);running=false;$('#nxBar').style.width='100%';set('nxPct','100%');stage(4,'Recherche terminée — résultats prêts.');setTimeout(()=>{overlay.classList.add('hidden');rows.forEach(r=>r.style.display='');$('#prospectEmpty')?.remove();set('prospectsCount',String(rows.length));toast('Recherche terminée : prospects trouvés.');view('prospects')},800)},15000)}
function cancel(){if(!running)return;clearTimeout(timer);clearInterval(interval);running=false;overlay?.classList.add('hidden');toast('Recherche Find annulée.')}button?.addEventListener('click',startSearch);$('#quickFind')?.addEventListener('click',startSearch);
const prompts=['Je cherche un photographe à Kinshasa...','Je cherche des entreprises qui ont besoin d’un site web...','Je cherche des clients pour mon agence...','Trouve-moi des prospects dans mon secteur...'];let pi=0,c=0,del=false,pt;function typePrompt(){if(!input||document.activeElement===input||input.value)return;const s=prompts[pi];if(!del){c++;input.placeholder=s.slice(0,c)+(c<s.length?'▌':'');if(c>=s.length){del=true;pt=setTimeout(typePrompt,1600);return}}else{c--;input.placeholder=s.slice(0,c)+(c?'▌':'');if(c<=0){del=false;pi=(pi+1)%prompts.length}}pt=setTimeout(typePrompt,del?35:55)}setTimeout(typePrompt,500);input?.addEventListener('focus',()=>{clearTimeout(pt);input.placeholder='Décrivez ce que vous recherchez…'});input?.addEventListener('blur',()=>{if(!input.value){c=0;del=false;typePrompt()}});
/* Friendly AI hand wave. */const title=$('#welcomeTitle');if(title&&!title.querySelector('.ai-hand'))title.insertAdjacentHTML('beforeend',' <span class="ai-hand" style="display:inline-block;animation:aiwave 1.8s ease-in-out infinite;transform-origin:70% 70%">👋</span>');const style=document.createElement('style');style.textContent='@keyframes aiwave{0%,100%{transform:rotate(0)}20%{transform:rotate(16deg)}40%{transform:rotate(-10deg)}60%{transform:rotate(13deg)}80%{transform:rotate(-5deg)}}';document.head.appendChild(style);
$('#newSearchBtn')?.addEventListener('click',()=>view('find'));$('#notifButton')?.addEventListener('click',()=>view('messages'));view('dashboard');